### PR TITLE
Add permutation and timeout options

### PR DESCRIPTION
**Pull request by joshua-rutherford**
Adds the ability to try different run list permutations in order to detect the unsolvable cookbooks issues.

### CODE REVIEW

**Comment by coderanger** [comment]
The timeout is managed by the server config, not the client.

**Comment by roostergator** [comment]
For what it's worth, the timeout option was to allow users to control the time spent searching for a solution in the event that the server had a very long timeout.  For some solution spaces the number of permutations is exceedingly large and if the server has a long timeout, solving each permutation can be quite time consuming.

**Comment by coderanger** [comment]
The whole point of knife-solve is to exactly match the behavior of chef-client when solving versions so you can see what versions would be used. You can always ctrl+c if something is taking too long, but knowing that it would have kept running had this been production is important.

**Comment by joshua-rutherford** [comment]
Just to close this out (and for my own notes), I understand the point of your plugin, but the chef-client solver (in chef 11 at least) is horrible.  It fails to solve for cookbook dependencies in a number of situations where the berkshelf solver finds solutions.  These failures can often be overcome by changing the order of dependencies in metadata.rb.  Thus, my permutations options allow for us to find a suitable solution and pin it in metadata.rb.  A better solution would be to fix the chef-client solver, but since that would require an update to chef in our environment this was a stop gap.  At any rate, we have rolled our own plugin that accomplishes these goals, thus I closed this.

**Pull request closed without merging**
